language: go
sudo: false
go:
  - "1.12"
install:
  - "go mod download"
  - go get -u -v gopkg.in/yaml.v2
env:
  global:
    - NAME=UClash
    - BINDIR=bin
script:
  - go build
before_deploy: make -j releases
deploy:
  provider: releases
  prerelease: true
  skip_cleanup: true
  api_key:
    secure: 26a68a123297018cd6e814fe8608d2091c990d33
  file: bin/*
  file_glob: true
  on:
    repo: oocococo/UClash
    branch: dev
    tags: true
